# Generated by Django 5.1.6 on 2025-05-29 06:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoRevisional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('valor_total', models.CharField(blank=True, max_length=100)),
                ('qtd_parcelas', models.IntegerField(blank=True, null=True)),
                ('parcelas_pagas', models.IntegerField(blank=True, null=True)),
                ('valor_parcela', models.CharField(blank=True, max_length=100)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='documentos/')),
            ],
        ),
    ]
