# Generated by Django 5.1.6 on 2025-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisao_segura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacaoEmprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('situacao_profissional', models.CharField(max_length=50)),
                ('valor_total', models.CharField(max_length=30)),
                ('renda_mensal', models.CharField(max_length=30)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
