# Generated by Django 5.1.6 on 2025-03-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0001_initial'),
    ]

    operations = [
    ]
