# Generated by Django 5.1.6 on 2025-03-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0003_alter_boleto_data_vencimento_alter_boleto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='data_vencimento',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleto',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20),
        ),
    ]
