# Generated by Django 5.1.6 on 2025-03-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_documento_titulo'),
    ]

    operations = [
    ]
