# Generated by Django 5.1.6 on 2025-03-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20250309_1736'),
    ]

    operations = [
    ]
