# Generated by Django 5.1.6 on 2025-05-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20250309_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoRevisional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('valor_total', models.CharField(max_length=30)),
                ('qtd_parcelas', models.IntegerField()),
                ('parcelas_pagas', models.IntegerField()),
                ('valor_parcela', models.CharField(max_length=30)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
