# Generated by Django 5.1.6 on 2025-05-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_calculorevisional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculorevisional',
            name='parcelas_pagas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculorevisional',
            name='qtd_parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculorevisional',
            name='valor_parcela',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='calculorevisional',
            name='valor_total',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
